import { Router } from 'express';
import businessesRouter from './businesses.js';
import reportsRouter from './reports.js';
import businessSkillsRouter from './business-skills.js';
import editsRouter from './edits.js';
import usageStatsRouter from './usage-stats.js';
import partnersRouter from './partners.js';
import marketplaceRouter from './marketplace.js';
import selfLearningRouter from './self-learning.js';
import privateSkillsRouter from './private-skills.js';
import workspacesRouter from './workspaces.js';
import environmentsRouter from './environments.js';
import roundtableStatsRouter from './roundtable-stats.js';
import sprintsRouter from './sprints.js';
import crmRouter from './crm.js';
import growthMeasuresRouter from './growth-measures.js';
import designerRouter from './designer.js';
import connectionsRouter from './connections.js';
import { ensureAdminCollections } from './collections.js';

ensureAdminCollections().catch(() => {});

const router = Router();
router.use(businessesRouter);
router.use(reportsRouter);
router.use(businessSkillsRouter);
router.use(editsRouter);
router.use(usageStatsRouter);
router.use(partnersRouter);
router.use(marketplaceRouter);
router.use(selfLearningRouter);
router.use(privateSkillsRouter);
router.use(workspacesRouter);
router.use(environmentsRouter);
router.use(roundtableStatsRouter);
router.use(sprintsRouter);
router.use(crmRouter);
router.use(growthMeasuresRouter);
router.use(designerRouter);
router.use(connectionsRouter);

export default router;
